name = "corridor-worker"
main = "src/index.ts"
compatibility_date = "2024-12-18"

[durable_objects]
bindings = [
  { name = "CLIPBOARD_SYNC", class_name = "ClipboardSyncDurableObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ClipboardSyncDurableObject"]

[env.production]
name = "corridor-worker"

[env.production.durable_objects]
bindings = [
  { name = "CLIPBOARD_SYNC", class_name = "ClipboardSyncDurableObject" }
]

[env.staging]
name = "corridor-worker-staging"
